kotlin.code.style=official
# kotlin.mpp.enableGranularSourceSetsMetadata=true  # REMOVED - deprecated in Kotlin 1.9.24
# kotlin.native.enableDependencyPropagation=false   # REMOVED - deprecated in Kotlin 1.9.24
kotlin.js.generate.executable.default=false
kotlin.android.buildTypeAttribute.keep=true

# Add this to disable the default hierarchy template warning:
kotlin.mpp.applyDefaultHierarchyTemplate=false

# Ignore incorrect dependencies warning for native target:
kotlin.native.ignoreIncorrectDependencies=true